### ISSUE TITLE
Should the default platform key abi for Windows be gcc7?

### ISSUE THREAD

**Issue by Gnimuc** [JuliaPackaging/BinaryProvider.jl#152]
Currently, it's `Window(:x86_64, compiler_abi=CompilerABI(:gcc4))` which is not compatible with the released Julia binaries. This explains https://github.com/staticfloat/LLVMBuilder/issues/34#issuecomment-431553292  and https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/399.

**Comment by visr** [comment]
@Gnimuc did your linked workaround work? And do you believe it may also help with https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/407? If so I'll try it as well.

**Comment by Gnimuc** [comment]
@visr here Clang or Cxx is a very special case, if the ABI is mismatched, Julia will instantly shout out "the specified procedure cannot be found.", so I'm not sure whether this is related or not. But you could try to build the binary using `BinaryProvider.Windows(:x86_64; compiler_abi=CompilerABI(:gcc7))` and then use the workaround to force BP to install the binary.

**Comment by visr** [comment]
Ah, the GCC7 build works great actually, no std::string troubles anymore in https://github.com/JuliaGeo/LibGEOS.jl/pull/56. Will update the other issue as well with this information.

**Comment by staticfloat** [comment]
X-ref my comment here: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/407#issuecomment-478141266

To summarize; I don't think changing the default platform is the right choice; instead we should intelligently determine that a tarball requires the `cxx11` ABI, then choose the right tarball.  We need to add a new compiler shard to get a viable libgfortran3 + cxx11 combination, and then we should be good to go.

**Comment by Gnimuc** [comment]
closed since this is not the right way to go, refer to discussions in  https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/407#issuecomment-478141266 for details.
