### ISSUE TITLE
__init__ not working for static compile

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPackaging/BinaryProvider.jl#157]
`probe_platform_engines!()` seems to be the problem here. I've actually been itching to refactor it for a while now - but it's odd combination of closures + global state make it pretty hard :D 

Since it's doing some platform probing, would it make sense to move it into the build step? Lunching a couple of processes on every init for information that should be available at installation time seems a bit problematic in any case.

**Comment by ararslan** [comment]
Fixed by #158
