### ISSUE TITLE
Interrupting a download (^C)

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/BinaryProvider.jl#17]
Perhaps this could be considered as using internals of the package, but anyway:

When Interrupting a `download` with e.g. ^C I get:

```
^CERROR (unhandled task failure): InterruptException:
Stacktrace:
 [1] wait() at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:? (repeats 3 times)
 [2] macro expansion at .../BinaryProvider/src/OutputCollector.jl:59 [inlined]
 [3] (::BinaryProvider.##2#4{Condition,Task})() at ./task.jl:335
```

and the call to `download` then throws a normal `ErrorException` that the download failed. In a situation where you try to download a file from different urls, you probably want to respond differently to a failure to download a file, and a ^C from the user.

Would it be possible to "handle the task failure" and propagate the `InterruptException` out to the caller of `download`?

**Comment by staticfloat** [comment]
Done, thanks for the good feedback.
