### ISSUE TITLE
v0.5.5 breaks ReadStat.jl on windows

### ISSUE THREAD

**Issue by davidanthoff** [JuliaPackaging/BinaryProvider.jl#172]
The recent v0.5.5 release breaks the ReadStat.jl build.jl on Windows. With any version of BinaryProvider.jl pre v0.5.5 everything works, with v0.5.5 on Windows I get this:
```
 Building StringEncodings → `C:\Users\david\.julia\packages\StringEncodings\ICuGB\deps\build.log`
  Building ReadStat ───────→ `C:\Users\david\.julia\dev\ReadStat\deps\build.log`
 Resolving package versions...
┌ Error: Error building `ReadStat`:
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ [ Info: Downloading https://github.com/davidanthoff/ReadStatBuilder/releases/download/v0.1.1-build.3/ReadStat.v0.1.1-dev.x86_64-w64-mingw32.tar.gz to C:\Users\david\.julia\dev\ReadStat\deps\usr\downloads\ReadStat.v0.1.1-dev.x86_64-w64-mingw32.tar.gz...
│ ERROR: LoadError: LoadError: LibraryProduct(nothing, ["libreadstat"], :libreadstat, "Prefix(C:\\Users\\david\\.julia\\dev\\ReadStat\\deps\\usr)") is not satisfied, 
cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] #write_deps_file#169(::Bool, ::Bool, ::Function, ::String, ::Array{Product,1}) at C:\Users\david\.julia\packages\BinaryProvider\A0sDa\src\Products.jl:419      
│  [3] write_deps_file(::String, ::Array{Product,1}) at C:\Users\david\.julia\packages\BinaryProvider\A0sDa\src\Products.jl:400
│  [4] top-level scope at none:0
│  [5] include at .\boot.jl:326 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1038
│  [7] include(::Module, ::String) at .\sysimg.jl:29
│  [8] include(::String) at .\client.jl:403
│  [9] top-level scope at none:0
│  [10] include at .\boot.jl:326 [inlined]
│  [11] include_relative(::Module, ::String) at .\loading.jl:1038
│  [12] include(::Module, ::String) at .\sysimg.jl:29
│  [13] include(::String) at .\client.jl:403
│  [14] top-level scope at none:0
│ in expression starting at C:\Users\david\.julia\dev\ReadStat\deps\build_ReadStat.v0.1.1-dev.jl:47
│ in expression starting at C:\Users\david\.julia\dev\ReadStat\deps\build.jl:3
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075
```

Could that release be reverted until this is fixed?

**Comment by thofma** [comment]
I think the issue reported https://github.com/Nemocas/Nemo.jl/issues/600 is the same. I changed nothing in the build script but suddenly GMPBuilder cannot be installed anymore. Note that there, the error was reported for arch linux.

**Comment by hhaensel** [comment]
This topic is already heavily discussed (#170)
It seems that deleting `.julia` "solves" the issue. It would be good to hear whether that solves the issue for you as well.
If you try, pleae only rename `.julia` so that you can revert to the non-functional behaviour.
@zgornel reported that 
```
success(`$(Base.julia_cmd()) -e "import Libdl; Libdl.dlopen(\"$(dl_esc_path)\")"`)
```
in [line 169 of Products.jl](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/master/src/Products.jl#L169) returns `false` in the context of package building but `true` at the REPL.
I realised that the `ENV` variable has a different `LOAD_PATH` depending on where it was called from.
`["@v#.#", "@stdlib"]` are missing when called from `Pkg.build`.
Could you try, whether
```
success(`$(Base.julia_cmd()) -e "import Libdl; splice!(LOAD_PATH, 2:1, ["@v#.#", "@stdlib"]); Libdl.dlopen(\"$(dl_esc_path)\")"`)
```
solves the issue? I have no failing system, so I can't do it ...
@staticfloat :
Shall we revert to `isolate=false` as default until the issue is solved?

**Comment by thofma** [comment]
I don't have a failing system,  so I cannot try this.

**Comment by staticfloat** [comment]
Isolation is quite important; there are certain .DLL's that will crash julia when attempting to be `dlopen()`'ed, which is a very bad experience for the user.  It's important for us to keep isolation as the default.

@davidanthoff do you have a local example of this failure?  Are you saying that if you pin BP to v0.5.4, it works?  What does the output say if you modify `C:\Users\david\.julia\dev\ReadStat\deps\build.jl` to have `verbose` set unconditionally to `true`?  (e.g. modify [this file](https://github.com/queryverse/ReadStat.jl/blob/master/deps/build_ReadStat.v0.1.1-dev.jl#L4) to say simply `verbose=true`)

**Comment by davidanthoff** [comment]
Locally, I can easily reproduce this, and when I locally pin BinaryProvider to v0.5.4 it all works again. I'm not working with deved versions of BinaryProvider to reproduce this.

I also run a nightly automated huge integration test for all queryverse packages, and that started failing with exactly this error on the day v0.5.5. was released. That whole process starts with a fresh environment every time it runs, so I think that very clearly pins it down to some change that was introduced by v0.5.5. You can see the latest log of those nightly builds [here](https://ci.appveyor.com/project/queryverse/queryversetests/build/job/1qx4wjgjja3l8np8).

I think the right process here is to revert very quickly, and not try to diagnose what is going on and fix. That can happen after things have reverted, but right now things are broken widely and that needs to be mitigated ASAP, IMHO.

**Comment by zgornel** [comment]
I agree with @davidanthoff this breaks too much stuff.

**Comment by hhaensel** [comment]
@davidanthoff :
would you mind running
```
julia -E "import Libdl; Libdl.open(\"C:\\Users\\david\\.julia\\dev\\ReadStat\\deps\\usr\\bin\\libreadstat-0.dll\")"
at a cmd prompt and report whether you receive an error?
```
I obtain:
```
IOStream(<file C:\Users\hh\.julia\dev\ReadStat\deps\usr\bin\libreadstat-0.dll>)
```

**Comment by davidanthoff** [comment]
```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.1 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> import Libdljulia> Libdl.open("C:\\Users\\david\\.julia\\dev\\ReadStat\\deps\\usr\\bin\\libreadstat-0.dll")
IOStream(<file C:\Users\david\.julia\dev\ReadStat\deps\usr\bin\libreadstat-0.dll>)

julia>
```
With `BinaryProvider#master`, and with a failing build step for ReadStat.jl.

**Comment by hhaensel** [comment]
That is reproducing the `isolate=false` case. Good to see rhat this is working.
Could you also run the above command a a bash prompt (not at the REPL)? That is closer to `isolate=true`.

**Comment by davidanthoff** [comment]
This:
```
 david@DANTHOFF-5820 > julia -E "import Libdl; Libdl.open(ARGS[1])" C:\Users\david\.julia\dev\ReadStat\deps\usr\bin\libreadstat-0.dll
IOStream(<file C:\Users\david\.julia\dev\ReadStat\deps\usr\bin\libreadstat-0.dll>)
```
I had to slightly change things because the escaping didn't work, but I think that code should do what you want, right?

**Comment by hhaensel** [comment]
Maybe then escaping is the point?
Are you working in a WSL or native windows?
In the latter case could you try from a regular `cmd` and from a powershell?

**Comment by davidanthoff** [comment]
This is from regular cmd:
```
C:\Users\david>\Users\david\AppData\Local\julia-1.1.1\bin\julia.exe -E "import Libdl; Libdl.open(ARGS[1])" C:\Users\david\.julia\dev\ReadStat\deps\usr\bin\libreadstat-0.dll
IOStream(<file C:\Users\david\.julia\dev\ReadStat\deps\usr\bin\libreadstat-0.dll>)

C:\Users\david>
```
This from Powershell:
```
 david@DANTHOFF-5820 > julia -E "import Libdl; Libdl.open(\"C:\\Users\\david\\.julia\\dev\\ReadStat\\deps\\usr\\bin\\libreadstat-0.dll\")"
ERROR: syntax: incomplete: invalid string syntax
 david@DANTHOFF-5820 >
```
No WSL involved, this is all native windows.

**Comment by hhaensel** [comment]
Very interesting, maybe the error depends on the platform that is used for issuing commands. I'm currently on my phone and don't have access to a computer.
I like your idea with the `ARGS` syntax. You might try entering that in the isolate==true case.

**Comment by davidanthoff** [comment]
I don't really follow, to be honest :) What should I do next? Also, I don't really understand why the issues about escaping from the command line are relevant for this question in general?

**Comment by hhaensel** [comment]
It prooved that different backends need different quotes, maybe this translates to the call where we had used explicit `\"` quoting.
I filed a PR #173 to test whether quotation marks are the problem.

**Comment by davidanthoff** [comment]
Ok, I think I understand now what is going on. I don't think this is related to the escaping, I think this is related to the fact that `libreadstat` has a dependency on `libiconv` and `libcharset`, both of which ship in StringEncodings.jl. But now if you start a new child process and try to just `dlopen` `libreadstat` it has no chance of locating `libiconv` and `libcharset`, which are stored in the `deps` folder of `StringEncodings`.

In the old days, without this isolation stuff, those two shared libraries would have been loaded already into the julia process, and so the resolution works.

I guess the basic question here is how this whole isolation story is meant to work for binaries that require other shared libraries that are shipping in another package?

**Comment by staticfloat** [comment]
Ah, yes.  That would definitely do it; however now that I check again, I kind of thought that BP switched to `isolate=false` by default.  Note that you will still see issues if no other code causes the dependent libraries to be loaded (e.g. you can try doing `using StringEncodings` first, to hopefully `dlopen()` those libraries first)

What version of BP are you seeing these problems on?

**Comment by hhaensel** [comment]
I'm still surprised that ReadStat builds without errors on my Windows 10 and Windows 7 and on WSL Ubuntu with BP 0.5.5.
Also `julia -E "import Libdl; Libdl.open(ARGS[1])" C:\Users\david\.julia\dev\ReadStat\deps\usr\bin\libreadstat-0.dll` did work from the command line without any preloading of other libaries ...?

**Comment by hhaensel** [comment]
Could it be connected to the LOADPATH variable ... ?

**Comment by hhaensel** [comment]
I need to mention that I had a typo in the command above. I wrote `Libdl.open` instead of `Libdl.dlopen`
So it should have been
julia -E "import Libdl; Libdl.dlopen(\"C:\\Users\\david\\.julia\\dev\\ReadStat\\deps\\usr\\bin\\libreadstat-0.dll\")" and the result should be some pointer.
Sorry for that.

**Comment by davidanthoff** [comment]
The following is what I get if I start julia in the folder where `libreadstat-0.dll` is located:
```julia
julia> import Libdl
julia> Libdl.dlopen("libreadstat-0.dll")
ERROR: could not load library "libreadstat-0.dll"
The specified module could not be found.

Stacktrace:
 [1] #dlopen#3(::Bool, ::Function, ::String, ::UInt32) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Libdl\src\Libdl.jl:109
 [2] dlopen at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Libdl\src\Libdl.jl:109 [inlined] (repeats 2 times)
[3] top-level scope at none:0

julia>
```
So that essentially confirms the hypothesis, that the problem here is that `libreadstat-0.dll` has binary dependencies on other shared libraries that it won't find in this isolated case.

**Comment by hhaensel** [comment]
@davidanthoff : You are completely right in your diagnosis. The loading of `libiconv-2.dll` fails.
I need to admit that all my thoughts about quoting were wrong.
But I also traced why I was not getting the error (thanks to Process Monitor) :-)
Atom installs a version of libiconv in `C:\Users\hh\AppData\Local\atom\app-1.38.1\resources\app.asar.unpacked\node_modules\dugite\git\mingw64\bin\` together with its git implementation.
If I rename this, I get the same error as @davidanthoff .
If I move to the folder where libiconv is stored and then call `dlopen`, it does work.
Also adding the directory to ENV["PATH"] works.

Just one note for correctness: I had a typo in the command above. I wrote `Libdl.open` instead of `Libdl.dlopen` So it should have been
`julia -E "import Libdl; Libdl.dlopen(\"C:\\Users\\david\\.julia\\dev\\ReadStat\\deps\\usr\\bin\\libreadstat-0.dll\")"` and the result should be some pointer.
Sorry for that.

**Comment by davidanthoff** [comment]
Wow, that is good detective work!

**Comment by hhaensel** [comment]
@staticfloat 
How do we continue here? Shall we role out the symlink modifications separately until we have a solution for the `isolate` issue? Or should we generate a version with `isolate=false`?
Maybe the other work on packaging is progressing fast enough to stop working here?

**Comment by BioTurboNick** [comment]
So I just encountered this error trying to install XXhash.jl on Windows.

This issue is 3 years old now. Anything I could help with?

**Comment by staticfloat** [comment]
Yes, the best thing to do is to update `xxhash` to use BinaryBuilder, generate an `xxhash_jll`, and use that instead of using BinaryProvider.

**Comment by staticfloat** [comment]
Looks like it already exists: https://github.com/JuliaBinaryWrappers/xxHash_jll.jl

So the julia package just needs to be updated to use that JLL instead of trying to download the binary deps in its `deps/build.jl` file.

**Comment by davidanthoff** [comment]
And I'm going to close this original issue, because ReadStat.jl has transitioned away from BinaryProvider years ago :)
