### ISSUE TITLE
Cache probe_platform_engines!

### ISSUE THREAD

**Issue by KristofferC** [JuliaPackaging/BinaryProvider.jl#18]
Running `probe_plastform_engines!` takes about 0.6 seconds. Perhaps it is worth to cache the results as a build step? This would require rebuilding when a user reinstalls new engines but a 0.6-second startup seems a bit high for something that quite rarely changes?

I'm looking a bit into downloading packages as tarballs in Pkg3 and am currently using this package and this causes startup time to increase a bit too much. If this issue is not in line with how the package is thought to be used, I could, of course, roll my own build script.

**Comment by staticfloat** [comment]
0.6 seconds?!  What?!  That's preposterous!

```
julia> @time BinaryProvider.probe_platform_engines!()
  0.009516 seconds (204 allocations: 12.154 KiB)
```

What kind of computer are you running this on?  Is it repeatedly `0.6` seconds, or is it only the first time?  Importing `BinaryProvider` itself does take me a little bit of time, my guess is that I need to provide more precompile hints:

```
julia> @time using BinaryProvider
  0.516573 seconds (595.26 k allocations: 33.188 MiB, 7.92% gc time)
```

**Comment by KristofferC** [comment]
Yes, I was totally wrong here. I must have mixed something up. Sorry for the noise.

**Comment by staticfloat** [comment]
I was worried for a bit there that Windows was being super-extra-stupid or something.  :)
