### ISSUE TITLE
option to specify endianness of download

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaPackaging/BinaryProvider.jl#2]
I know that Julia has been little-endian focused, and I agree with that.  Now that people are starting to work with specialty data and compressed files generated with specialized hardware, allowing the user of this to state by keyword setting that the target (file or compressed collection of files) has been stored big-endian.
(I have no such need).

**Comment by staticfloat** [comment]
We have good multi-architecture support in this package, allowing the user to specify things such as `Linux(:ppc64le, :glibc)` to unambiguously refer to a PPC 64-bit Little-Endian machine running Linux, using `glibc` as the backing libc, so I think within that system we will be able to deal with any kind of exotic architecture that a user wishes to use.  Please feel free to open new issues once more concrete needs are discovered!
