### ISSUE TITLE
Downloaded binaries get used no matter what

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaPackaging/BinaryProvider.jl#27]
* When you change the build script url, to e.g. use a new tag with new binaries, a user running `Pkg.build("MyPackage")` will reuse whatever binary is already downloaded

* When the download is corrupted, or from an older tag with non matching hashes, build fails, even though deleting and downloading the new binary would resolve the problem

* Downloading from non existent urls works as if nothing is wrong, the empty file stays in the download folder and gets used, but fails with a hash not match error

Thanks for all the effort!

**Comment by ChrisRackauckas** [comment]
That seems to have been the issue here: https://github.com/JuliaDiffEq/Sundials.jl/issues/151

**Comment by staticfloat** [comment]
> * When you change the build script url, to e.g. use a new tag with new binaries, a user running Pkg.build("MyPackage") will reuse whatever binary is already downloaded

Yes, from the point of view of `BinaryProvider`, the dependency is already satisfied.  It is quite difficult for us to enforce this properly, I'm open to suggestions on what kind of an API you would like for this; we could introduce hash checks into `deps/build.jl` to force version upgrades.

> When the download is corrupted, or from an older tag with non matching hashes, build fails, even though deleting and downloading the new binary would resolve the problem

You can get it to do what you want by setting `force` to `true` within `download_*` functions.

> Downloading from non existent urls works as if nothing is wrong, the empty file stays in the download folder and gets used, but fails with a hash not match error

[We have a test](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/2ca0f33871e03f3e7eb0287701152352699e7f97/test/runtests.jl#L594-L597) to ensure this doesn't happen.  Can you give me an example of this happening for you?

**Comment by SimonDanisch** [comment]
>Can you give me an example of this happening for you?

I tried to reproduce the example from memory and now I get a 404 error instead of downloading the file. 
Could there be a new test, or might this be a problem with my machine (i'm at a different one right now - I had that problem on a pretty used linux machine and now I'm on a 3 days old linux machine).

**Comment by staticfloat** [comment]
Well, that particular test has been there for at least 5 months, so I think probably not.

Here's what could be happening; your DNS provider or some kind of proxy is giving you a file that your computer downloads with an HTTP 200 OK response.  If you don't pass `force=true` BinaryProvider will freak out and not automatically try to re-download, I don't think.  So if this is a file that you control and that you are okay with potentially clobbering, use `force=true`.

**Comment by SimonDanisch** [comment]
Ok, so I guess `force = true` will be a better default for my build scripts - seems more stable in corruption cases...

**Comment by staticfloat** [comment]
Yes, precisely.

**Comment by SimonDanisch** [comment]
Great, thanks! Should this be the default in the auto generated scripts?

**Comment by staticfloat** [comment]
Yes, I think that makes sense.

**Comment by staticfloat** [comment]
Please do open an issue against the relevant repo if that's not the case.  I'm going to close this now.
