### ISSUE TITLE
Hash Mismatch! Error.

### ISSUE THREAD

**Issue by rudrasohan** [JuliaPackaging/BinaryProvider.jl#28]
I was trying to build `Pkg.build("Sundials")` when I got this error.

`LoadError: Hash Mismatch!
  Expected sha256:   f34ad4faa4d0c9841e15348a48c8ab5780af56da23af9d46274192c6bbcf1049
  Calculated sha256: 4b5f9e8781909e722c51e134f68e83e6ca99ab612a5dab8ecc3e0f8057cfcdfd
while loading /home/sohan/.julia/v0.6/Sundials/deps/build.jl, in expression starting on line 54`

Can anyone tell what's causing this error ?

Note:- I'm behind a campus-proxy, but other julia packages get installed without a problem. 
           I'm on Ubuntu 16.04 LTS(Xenial amd64) using juila v0.6.0.

**Comment by staticfloat** [comment]
This could be due to a campus proxy problem.  Can you post the whole error?  It should tell us what file is not hashing properly.

**Comment by rudrasohan** [comment]
I fixed the error recently. I upgraded my Julia version from v0.6.0 to v0.6.2 and redownload the Julia differential equations and Sundials built just fine. No hash mismatch even under campus proxy. So I think the error might have been with the version of Julia.

**Comment by staticfloat** [comment]
Alright, I'm going to close this issue then, please feel free to reopen if something else goes wrong
