### ISSUE TITLE
Could deps.jl use relative paths instead of absolute?

### ISSUE THREAD

**Issue by quinnj** [JuliaPackaging/BinaryProvider.jl#47]
Ran into an issue today trying to deploy an app where my julia image was built in our build pipeline (jenkins), including building/precompiling packages like MbedTLS.jl, but then when pushed to the actual deploy server fails because the `deps.jl` file for MbedTLS.jl was hard-coded w/ the absolute path from the build node. Could we just use relative paths in the generated deps.jl file so we don't run into these issues? Currently I'm having to "rebuild" on each node.

**Comment by staticfloat** [comment]
Yeah, I don't see a problem with this.  Check out https://github.com/JuliaPackaging/BinaryProvider.jl/pull/51 for how I'm planning to do it.  Go ahead and check out that branch, then delete your `deps.jl` file and re-run `Pkg.build(<package name>)` to regenerate the `deps.jl` file to see if it now gives relative paths.

Note that your `build.jl` file will need to write out a `deps.jl` file even if everything is satisfied for that to work.  As an example, the `build.jl` file for MbedTLS doesn't do that.

**Comment by staticfloat** [comment]
This should be fixed now.
