### ISSUE TITLE
symbol renaming to avoid library conflicts

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/BinaryProvider.jl#54]
It might be nice to provide an easy way to rename all the symbols in a library, to avoid conflicts with other external libraries like we encountered in JuliaLang/julia#4923.

For example, if you included GNU `objcopy` in your cross-compile setup, then something like `--prefix-symbols` could be used for this without modifying any source code.

**Comment by staticfloat** [comment]
This is a neat idea, and we should think about it.  However, this should be moved to the [`BinaryBuilder.jl`](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues) issue tracker.  Let's continue discussion there.
