### ISSUE TITLE
Allow `busybox` as download/compress engine

### ISSUE THREAD

**Issue by Keno** [JuliaPackaging/BinaryProvider.jl#73]
Busybox in single-executable mode, can be called as `busybox wget` and `busybox tar`. If `busybox` is available, we should be able to use it like that, even if the individual symlinks are not available.

**Comment by staticfloat** [comment]
Is there a configuration in which `busybox` cannot be used in this way?  E.g. is searching for `busybox` sufficient, or do I need to do some kind of test to make sure this functionality is available?

**Comment by Keno** [comment]
I believe it is possible to configure busybox without those tools, so we'd probably have to detect whether buysbox errors when you try to call it that way.

**Comment by staticfloat** [comment]
I wrote up some tests to try it, but my `busybox wget` doesn't support HTTPS.   Does yours?

**Comment by Keno** [comment]
Yes:
```
# busybox wget https://github.com/
Connecting to github.com (192.30.253.112:443)
index.html           100% |*******************************| 54869   0:00:00 ETA
# cat index.html | wc
    826    3966   54869
```

**Comment by staticfloat** [comment]
Okay, looks like Arch's busybox [doesn't have HTTPS support built-in](https://git.archlinux.org/svntogit/community.git/tree/trunk/config?h=packages/busybox#n945), which is unfortunate.  I haven't figured out a way to check whether `busybox` has support for `https` short of actually trying to download something, which I would like to avoid.

**Comment by Keno** [comment]
Maybe just fallback to busybox as an option of last resort?

**Comment by staticfloat** [comment]
https://github.com/JuliaPackaging/BinaryProvider.jl/pull/75

**Comment by staticfloat** [comment]
Looks like the `busybox` you get on Ubuntu and Debian doesn't support HTTPS out of the box, so testing this is going to be a pain.  What system are you using where `busybox` is a preferred system?
