### ISSUE TITLE
need import Compat.Libdl on 0.7

### ISSUE THREAD

**Issue by stevengj** [JuliaPackaging/BinaryProvider.jl#89]
There seem to be several places that use `Libdl.foo` without first importing the Libdl module, which is required on 0.7.   (For 0.6 compatibility, `import Compat.Libdl`).  For example

* [here](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/865e9ce4e041ea2ef9c841cac5fbc9c1f4eac055/src/Products.jl#L168)
* [here](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/865e9ce4e041ea2ef9c841cac5fbc9c1f4eac055/src/Products.jl#L440)

The latter case is in generated code for `deps.jl` so it triggers deprecation warnings in packages (see e.g. stevengj/Blosc.jl#56).

**Comment by ararslan** [comment]
To avoid introducing a dependency on Compat everywhere, we could change the latter case to
```diff
--- a/src/Products.jl
+++ b/src/Products.jl
@@ -437,6 +437,9 @@ function write_deps_file(depsjl_path::AbstractString, products::Vector{P};
             # For Library products, check that we can dlopen it:
             if typeof(product) <: LibraryProduct
                 println(depsjl_file, """
+                    if VERSION >= v"0.7.0-DEV.3382"
+                        import Libdl
+                    end
                     if Libdl.dlopen_e($(varname)) == C_NULL
                         error("\$($(varname)) cannot be opened, $(rebuild)")
                     end
```

**Comment by stevengj** [comment]
@ararslan, that makese sense, but the `import Libdl` should appear earlier, above the `function check_deps()` declaration.

**Comment by ararslan** [comment]
Oops, so what I've done in #90 should be fixed then. :stuck_out_tongue:
